BD-incollo-master/urls.py
"""
    This file is part of BD-incollo.

    BD-incollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BD-incollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with BD-incollo.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *

from Paste.models import Paste
from Paste.views import add_paste, view_paste, download_paste, report_paste, view_latest_pastes, search_pastes, discuss_paste, compare_pastes, mark_as_spam, view_latest_user_pastes, delete_paste

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^media/(.*)', 'django.views.static.serve', {'document_root': '/home/incollo/Incollo/media'}),
    (r'^media-admin/(.*)', 'django.views.static.serve', {'document_root': '/home/incollo/Incollo/media-admin'}),
    (r'^admin/(.*)', admin.site.root),
    (r'^about', 'django.views.generic.simple.direct_to_template', {'template': 'about.html'}),
    (r'^bug', 'django.views.generic.simple.direct_to_template', {'template': 'bug.html'}),
    (r'^news', 'django.views.generic.simple.direct_to_template', {'template': 'news.html'}),
    (r'^$', add_paste),
    (r'^(?P<hash_key>[A-Fa-f0-9]+)$', view_paste),
    (r'^download/(?P<hash_key>[A-Fa-f0-9]+)', download_paste),
    (r'^report/(?P<hash_key>[A-Fa-f0-9]+)', report_paste),
    (r'^discuss/(?P<hash_key>[A-Fa-f0-9]+)', discuss_paste),
    (r'^compare/(?P<first_hash_key>[A-Fa-f0-9]+)/(?P<second_hash_key>[A-Fa-f0-9]+)', compare_pastes),
    (r'^latest-pastes$', view_latest_pastes),
    (r'^latest-personal-pastes$', view_latest_user_pastes),
    (r'^search/$', search_pastes),
    (r'^spam/(?P<hash_key>[A-Fa-f0-9]+)$', mark_as_spam),
    (r'^delete/(?P<hash_key>[A-Fa-f0-9]+)', delete_paste),
    (r'^comments/', include('django.contrib.comments.urls')),

)

assesment/Patebin_clone/Patebin_clone/urls.py
from django.contrib import admin
from django.conf.urls import include,url

urlpatterns = [
    url(r'^', include('pastebin_app.urls')),
    url(r'^admin/', admin.site.urls),
]

toDo_app/urls.py
from django.urls import path
from toDo_app.views import AddTodo, DeleteAll, DeleteItem, TodoView,Upload

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('addTodo/', AddTodo.as_view()),
    path('', TodoView.as_view()),
    path('deleteTodo/<int:todo_id>/',DeleteItem.as_view()),
    path('deleteAll/', DeleteAll.as_view()),
    path('upload/', Upload.as_view(), name = 'upload')
    #path('imageList/', Image_list.as_view(), name = 'images')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

toDo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toDo_app.urls')),
]

BD-incollo-master/Paste/models.py
"""
    This file is part of BD-incollo.

    BD-incollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BD-incollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with BD-incollo.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.db import models
import datetime
import time
import hashlib
import random

class Paste(models.Model):
    entry_date = models.DateTimeField(auto_now_add=True)
    last_view = models.DateTimeField(auto_now_add=True, auto_now=False)
    body = models.TextField()
    language = models.CharField(max_length=50)
    title = models.CharField(max_length=50,blank=True)
    private = models.BooleanField(default=False)
    in_response_to = models.ForeignKey('self',blank=True,null=True)
    hash_key = models.CharField(max_length=50)
    
    class Meta:
        ordering = ["-entry_date"]
        
    def hash(self):
        time_now_epoch = datetime.datetime.now()
        time_now_seconds = int(time.mktime(time_now_epoch.timetuple()))
        return str(hashlib.sha1(str(abs(
                (hash(self) * random.randint(1,5) + time_now_seconds)
            ))).hexdigest())[4:13]
    
    @models.permalink
    def get_absolute_url(self):
        return ('Paste.views.view_paste', [str(self.hash_key)])

    def __unicode__(self):
        return ((self.title or "Untitled Paste") + " - " + (self.language or "No Language Defined"))
    

BD-incollo-master/Paste/forms.py
"""
    This file is part of BD-incollo.

    BD-incollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BD-incollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with BD-incollo.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.forms import ModelForm
from django import forms
from models import Paste

class PasteForm(ModelForm):
    '''Form for inserting a Paste
    '''
    class Meta:
        model = Paste
        fields = ('title', 'language','private','body')

REPORT_REASONS = (
    ('spam', 'Spam'),
    ('warez', 'Serials/Link to Warez'),
    ('other', 'Other'),
)

class ReportForm(forms.Form):
    '''Form for reporting a Paste
    '''
    reason = forms.ChoiceField(choices=REPORT_REASONS,widget=forms.RadioSelect())
    comment = forms.CharField(widget=forms.Textarea(attrs={'size':'10'}))
    email = forms.EmailField()

BD-incollo-master/Paste/views.py
"""
    This file is part of BD-incollo.

    BD-incollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BD-incollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with BD-incollo.  If not, see <http://www.gnu.org/licenses/>.
    
    This file contains all the views accessible by a HTTP request.
"""

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, Http404
from django.db.models import Q
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.conf import settings
from django.template import RequestContext

from models import Paste
from forms import PasteForm, ReportForm

from utils import is_collision
from utils import clean_pastes
from utils import update_last_view
from utils import colorize_syntax
from utils import remember_the_paste
from utils import is_owner_of

from diff import get_html_diff_list

from honeypot.decorators import check_honeypot

@check_honeypot
def add_paste(request):
    """ Adds a new paste in the database
    """
    clean_pastes()
    if request.method == 'POST': # If the form has been submitted...
        form = PasteForm(request.POST) # creates a PasteForm object with the posted data
        if form.is_valid():
            tempPaste = form.save(commit=False)
            tempPaste.hash_key = tempPaste.hash()
            # recompute the hash key if there is a collision
            while (is_collision(tempPaste.hash_key)): 
                tempPaste.hash_key = tempPaste.hash()   
            tempPaste.save()
            remember_the_paste(request,tempPaste)
            return HttpResponseRedirect(tempPaste.get_absolute_url()) # visualize the Paste
    else:
        form = PasteForm() # A new form
    return render_to_response('paste_form.html', {
        'error_message': None,
        'form': form,
    },context_instance=RequestContext(request))

def search_pastes(request):
    """ Queries the database and searches public Pastes
    """
    query = request.GET.get('q','')
    entries = []
    if query:
        qset = (
            Q(title__icontains=query) |
            Q(language__icontains=query) |
            Q(body__icontains=query)
        )
        entries = Paste.objects.filter(qset,private=False).distinct()

    return render_to_response('search_pastes.html', {
        'entries': entries,
        'query': query,
    },context_instance=RequestContext(request))


def view_latest_pastes(request):
    """ Visualizes the last Pastes
    """
    entries = []
    try:
        entries = Paste.objects.filter(private=False)[:settings.MAX_PASTES_FOR_LATEST_PASTES_SECTION]
    except IndexError:
        entries = Paste.objects.filter(private=False)
    return render_to_response('view_latest_pastes.html', {
        'personal_pastes': False,
        'entries': entries,
    },context_instance=RequestContext(request))


def view_paste(request,hash_key):
    """ Given its hash key, visualizes it
    """
    hash_key = str(hash_key)
    entry = get_object_or_404(Paste, hash_key=hash_key)
    update_last_view(entry)
    clean_pastes()
    # generates syntax highlighting
    colorized_body = colorize_syntax(entry.body,entry.language)

    # creates the form for reporting the Paste to admin
    report_form = ReportForm()
    report_message = ""

    if request.method == 'GET':
        if request.GET.has_key("reported"):
            report_message = "Thank you for your report!"
        if request.GET.has_key("error_report"):
            report_message = "There has been an error. Please contact an administrator!"
    return render_to_response('view_paste.html', {
        'entry': entry,
        'colorized_body': colorized_body,
        'report_form': report_form,
        'report_message': report_message,
    },context_instance=RequestContext(request))

def download_paste(request,hash_key):
    """ Given its hash key, returns the Paste as plain text file
    """
    hash_key = str(hash_key)
    entry = get_object_or_404(Paste, hash_key=hash_key)
    update_last_view(entry)
    clean_pastes()
    response = HttpResponse(mimetype='text/plain')  # set the mimetype for a text file
    response.write(entry.body)                      # write it to the response
    response['Filename'] = 'incollo.com-'+ str(entry.hash_key) +'.txt'
    response['Content-Disposition'] = 'attachment; filename=incollo.com-'+ str(entry.hash_key) +'.txt'
    return response


def report_paste(request,hash_key):
    """ Sends a e-mail to the site administrator, reporting a Paste
    """
    entry = get_object_or_404(Paste, hash_key=hash_key)
    report_message = ""
    if request.method == "POST":
        form = ReportForm(request.POST)
        if form.is_valid():
            reason = form.cleaned_data['reason']
            comment = form.cleaned_data['comment']
            email = form.cleaned_data['email']
            # prepare the e-mail with data submitted by the user
            report_body = ''' Paste located at http://incollo.com/%s has been reported with reason '%s'.\n Additional comment: %s .\n User e-mail: %s ''' %  (hash_key, reason, comment, email)
            # send the e-mail
            report = EmailMessage('Report abuse from bd-incollo!',
                                  report_body,
                                  to=settings.MANAGERS[0],
                                  )
            report.send()
            report_message = "Thank you for your report!"
        else:
            report_message = "Some fields are either missing or invalid, please complete the form"    
    
    report_form = ReportForm()  # create a form for reporting the Paste (if needed)
    return render_to_response('report_paste.html', {
        'report_message': report_message,
        'entry': entry,
        'report_form': report_form,
    },context_instance=RequestContext(request))

@check_honeypot
def discuss_paste(request,hash_key):
    """ Creates a new Paste, linking it with a previous one.
        In this way, Pastes may be enhanced and diffs can be performed
    """
    paste_discussed = get_object_or_404(Paste, hash_key=hash_key)
    update_last_view(paste_discussed)
    clean_pastes()
    form = PasteForm(instance=paste_discussed)
    language = paste_discussed.language
    private = paste_discussed.private
    
    if request.method == 'POST': 
        form = PasteForm(request.POST)
        if form.is_valid():
            tempPaste = form.save(commit=False)
            tempPaste.hash_key = tempPaste.hash()
            # recompute the hash key if there is a collision
            while (is_collision(tempPaste.hash_key)): 
                tempPaste.hash_key = tempPaste.hash()
            tempPaste.in_response_to = paste_discussed
            tempPaste.private = private
            tempPaste.save()
            return HttpResponseRedirect(tempPaste.get_absolute_url()) # visualize the Paste'''
    return render_to_response('discuss_paste.html', {
        'error_message': None,
        'paste_discussed': paste_discussed,
        'form': form,
    },context_instance=RequestContext(request))


def compare_pastes(request,first_hash_key, second_hash_key):
    """ Given their hash keys, retrieves two Pastes and compares them.
        Diff is computed using diff-match-patch by Neil Fraser (http://code.google.com/p/google-diff-match-patch/)
        Line numbering for snippets is computed manually, only for this view
    """
    first_hash_key = str(first_hash_key)
    second_hash_key = str(second_hash_key)
    first_entry = get_object_or_404(Paste, hash_key=first_hash_key)
    second_entry = get_object_or_404(Paste, hash_key=second_hash_key)
    
    update_last_view(first_entry)
    update_last_view(second_entry)
    clean_pastes()
    
    
    html_diff = get_html_diff_list(first_entry,second_entry)

    return render_to_response('compare_pastes.html', {
        'diff': html_diff,
    },context_instance=RequestContext(request))

def view_latest_user_pastes(request):
    ''' Looks for the "user_pastes" session Cookies. If found, searches the corresponding Pastes
        and returns them to the template.
    '''
    try:
        user_pastes = Paste.objects.filter(id__in=request.session.get('user_pastes', None))
    except:
        user_pastes = None
   
    return render_to_response('view_latest_pastes.html', {
        'personal_pastes': True,
        'entries': user_pastes,
    },context_instance=RequestContext(request))

def delete_paste(request,hash_key):
    ''' Given its hash key, deletes a Paste if and only if the user is also
        the owner of the Paste
    '''
    hash_key = str(hash_key)
    paste = get_object_or_404(Paste,hash_key=hash_key)
    if is_owner_of(request,paste):
        request.session['user_pastes'].remove(paste.id)
        paste.delete()
        return HttpResponseRedirect(reverse(view_latest_user_pastes))
    else:
        raise Http404


def mark_as_spam(request,hash_key):
    """ Given the hash keys, retrieves the corresponding Paste, marks it as Spam, deletes it
        and returns the result of the operation
    """
    entry_hash_key = str(hash_key)
    if not request.user.is_superuser:
        return HttpResponse(False, mimetype="# text/ecmascript")
    try:
        entry = Paste.objects.get(hash_key=entry_hash_key)
        submit_spam(request,entry.body)
        entry.delete()
    except: 
        return HttpResponse(False, mimetype="# text/ecmascript")

BD-incollo-master/templates/505.html
{% extends "base.html" %}
{% block title %}
Incollo.com - a free collaborative debugging tool - View Paste
{% endblock %}

{% block center %}
        <h1>
            Error 505. For Sure!
        </h1>
	
        <div class="entry">
	The administrator has just been warned. Why don't you write him an e-mail telling him what you
	were doing?
        </div>
{% endblock %}

BD-incollo-master/templates/base.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/media/style.css" />
    <script type="text/javascript" src="/media/jquery.js"></script>
    <script type="text/javascript" src="/media/jquery.field.js"></script>
    <script type="text/javascript" src="/media/thickbox.js"></script>
</head>
<body>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? 
"https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + 
"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-5685155-2");
pageTracker._trackPageview();
</script>
<script type="text/javascript">

$(function(){
    $('a.select_all_text').click(function(){
        $('textarea.code_plain').select();
        return false;
    });
});

$(function(){
    $('a.new-window').click(function(){
        window.open(this.href);
        return false;
    });
});

</script>
    <div class="menu">
        <div class="menuleft">
                <a href="/">New Paste</a>
		<a href="/latest-pastes">View Last Pastes</a>
		<a href="/latest-personal-pastes">View Your Pastes</a>
		<a href="/news" class="new">News</a>
                <a href="/about">About</a>
                <a href="/bug">Found a Bug / Request Features</a>
        </div>
        <div class="menuright">
                <form action="/search" method="get">
                    <div>
                        <input type="text" name="q" id="id_query" value="{{query|escape}}" />
                        <input type="submit" id="id_search" value="Search" />
                    </div>
                </form>
        </div>
    </div>
    <div class="center">
        <div class="content">
    {% block center %}{% endblock %}
        </div>
    </div>
    <div class="footer">
        <a href="http://incollo.com/">Incollo.com</a>, powered by <a href="http://bd-things.net/projects/bd-incollo/">BD-incollo</a>.
        For more information, see the <a href="/about">about page</a> and <a href="http://bd-things.net">bodom_lx blog</a>
    </div>
</body>
</html>

BD-incollo-master/templates/discuss_paste.html
{% extends "base.html" %}
{% block title %}
Incollo.com - a free collaborative debugging tool - New Paste
{% endblock %}

{% block center %}
        <h1>
            Enhance Paste
        </h1>
	{% if error_message %}
	    <div class="error">{{error_message}}</div>
	{% endif %}
        <h3>
            <label for="id_language">Language of this Paste: </label>
            <input type="text" value="{{paste_discussed.language}}"/>
	    <label for="id_language">Will be private: </label>
            <input type="text" value="{{paste_discussed.private}}"/>
        </h3>
	<div class="sub-header">
	    <script type="text/javascript">
	    $(document).ready(function(){
		$("div.in-response-to").hide();
		$("div.error").hide();
		$("div.in-response-to").fadeIn("slow");
		$("div.error").fadeIn("slow");
	    });

	    $(function(){
		$('#new-paste').submit(function(){
		    $("div.message").hide();
		    if($('#id_body').val()!=""){
			$("div.message").css("border-color","#cccccc");
			$("div.message").html("Submitting Paste...").fadeIn();
			return true;
		    }else{
			$("div.message").css("border-color","red");
			$("div.message").html("Please provide a text for your Paste").fadeIn();
			return false;
		    }
		});
	    });

	    </script>
	    <div class="in-response-to">
	    <h3>
		<label for="id_permalink">In response to: </label>
		<a id="original-paste" href="{{paste_discussed.get_absolute_url}}">{{paste_discussed}}</a>, posted on {{paste_discussed.entry_date|date}}&nbsp;
	    </h3>
	    </div>
	</div>
<div class="message" style="display:none"></div>
<form method="post" action="/discuss/{{paste_discussed.hash_key}}" class="paste" id="new-paste">
    <table class="new_paste">
	<tr>
	    <td class="left">
		<label for="id_body">Entry:</label>
	    </td>
	    <td class="center">
		{{ form.body }}
	    </td>
	</tr>
	<tr>
            <td class="left">
                <label for="id_title">Title:</label>
            </td>
            <td class="center">
                {{ form.title }}
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
            <td>
		<input type="hidden" name="language" id="id_language" value="{{paste_discussed.language}}" />
		{% if paste_discussed.private %}
		<input type="hidden" name="private" id="id_private" value="On" />
                {% else %}
		<input type="hidden" name="private" id="id_private" value="Off" />
		{% endif %}
                <input type="submit" value="Paste!" id="id_submit" />
            </td>
        </tr>

    </table>
</form>
{% endblock %}

BD-incollo-master/templates/paste_form.html
{% extends "base.html" %}
{% load honeypot %}
{% block title %}
Incollo.com - a free collaborative debugging tool - New Paste
{% endblock %}

{% block center %}

{% if error_message %}
    <script type="text/javascript">
	    $(document).ready(function(){
		$("div.error").fadeIn("slow");
	    });
    </script>
    <div class="error">{{error_message}}</div>
{% endif %}
<script type="text/javascript">

$(function(){
    $('#new-paste').submit(function(){
	$("div.message").hide();
	if($('#id_body').val()!=""){
	    $("div.message").html("Submitting Paste...").fadeIn();
	    return true;
	}else{
	    $("div.message").css("border-color","red");
	    $("div.message").html("Please provide a text for your Paste").fadeIn();
	    return false;
	}
    });
});
</script>
<div class="message" style="display:none"></div>
<form method="post" action="/" class="paste" id="new-paste">
    <table class="new_paste">
	<tr>
	    <td class="left">
		<label for="id_body">Entry:</label>
	    </td>
	    <td class="center">
		{{ form.body }}
	    </td>
	</tr>
	<tr>
	    <td class="left">
                <label for="id_language">Language:</label>
	    </td>
	    <td class="center">
                <select id="id_language" name="language">
                    <option value="text">No filter</option>
                    <option value="as" >ActionScript</option>
                    <option value="as3" >ActionScript 3</option>
                    <option value="apacheconf" >ApacheConf</option>
                    <option value="bbcode" >BBCode</option>
                    <option value="bash" >Bash</option>
                    <option value="bat" >Batchfile</option>
                    <option value="befunge" >Befunge</option>
                    <option value="boo" >Boo</option>
                    <option value="brainfuck" >Brainfuck</option>
                    <option value="c" >C</option>
                    <option value="csharp" >C#</option>
                    <option value="cpp" >C++</option>
                    <option value="css" >CSS</option>
                    <option value="css+django" >CSS+Django/Jinja</option>
                    <option value="css+genshitext" >CSS+Genshi Text</option>
                    <option value="css+mako" >CSS+Mako</option>
                    <option value="css+myghty" >CSS+Myghty</option>
                    <option value="css+php" >CSS+PHP</option>
                    <option value="css+erb" >CSS+Ruby</option>
                    <option value="css+smarty" >CSS+Smarty</option>
                    <option value="cheetah" >Cheetah</option>
                    <option value="clojure" >Clojure</option>
                    <option value="common-lisp" >Common Lisp</option>
                    <option value="d" >D</option>
                    <option value="dpatch" >Darcs Patch</option>
                    <option value="control" >Debian Control file</option>
                    <option value="sourceslist" >Debian Sourcelist</option>
                    <option value="delphi" >Delphi</option>
                    <option value="diff" >Diff</option>
                    <option value="django" >Django/Jinja</option>
                    <option value="dylan" >Dylan</option>
                    <option value="erb" >ERB</option>
                    <option value="erlang" >Erlang</option>
                    <option value="fortran" >Fortran</option>
                    <option value="gas" >GAS</option>
                    <option value="genshi" >Genshi</option>
                    <option value="genshitext" >Genshi Text</option>
                    <option value="pot" >Gettext Catalog</option>
                    <option value="gnuplot" >Gnuplot</option>
                    <option value="groff" >Groff</option>
                    <option value="html" >HTML</option>
                    <option value="html+cheetah" >HTML+Cheetah</option>
                    <option value="html+django" >HTML+Django/Jinja</option>
                    <option value="html+genshi" >HTML+Genshi</option>
                    <option value="html+mako" >HTML+Mako</option>
                    <option value="html+myghty" >HTML+Myghty</option>
                    <option value="html+php" >HTML+PHP</option>
                    <option value="html+smarty" >HTML+Smarty</option>
                    <option value="haskell" >Haskell</option>
                    <option value="ini" >INI</option>
                    <option value="irc" >IRC logs</option>
                    <option value="io" >Io</option>
                    <option value="java" >Java</option>
                    <option value="jsp" >Java Server Page</option>
                    <option value="js" >JavaScript</option>
                    <option value="js+cheetah" >JavaScript+Cheetah</option>
                    <option value="js+django" >JavaScript+Django/Jinja</option>
                    <option value="js+genshitext" >JavaScript+Genshi Text</option>
                    <option value="js+mako" >JavaScript+Mako</option>
                    <option value="js+myghty" >JavaScript+Myghty</option>
                    <option value="js+php" >JavaScript+PHP</option>
                    <option value="js+erb" >JavaScript+Ruby</option>
                    <option value="js+smarty" >JavaScript+Smarty</option>
                    <option value="llvm" >LLVM</option>
                    <option value="lighty" >Lighttpd configuration file</option>
                    <option value="lhs" >Literate Haskell</option>
                    <option value="logtalk" >Logtalk</option>
                    <option value="lua" >Lua</option>
                    <option value="moocode" >MOOCode</option>
                    <option value="basemake" >Makefile</option>
                    <option value="make" >Makefile</option>
                    <option value="mako" >Mako</option>
                    <option value="matlab" >Matlab</option>
                    <option value="matlabsession" >Matlab session</option>
                    <option value="minid" >MiniD</option>
                    <option value="trac-wiki" >MoinMoin/Trac Wiki markup</option>
                    <option value="mupad" >MuPAD</option>
                    <option value="mysql" >MySQL</option>
                    <option value="myghty" >Myghty</option>
                    <option value="nasm" >NASM</option>
                    <option value="nginx" >Nginx configuration file</option>
                    <option value="numpy" >NumPy</option>
                    <option value="ocaml" >OCaml</option>
                    <option value="objective-c" >Objective-C</option>
                    <option value="php" >PHP</option>
                    <option value="pov" >POVRay</option>
                    <option value="perl" >Perl</option>
                    <option value="python" >Python</option>
                    <option value="python3" >Python 3</option>
                    <option value="pytb" >Python Traceback</option>
                    <option value="pycon" >Python console session</option>
                    <option value="rhtml" >RHTML</option>
                    <option value="raw" >Raw token data</option>
                    <option value="redcode" >Redcode</option>
                    <option value="rb" >Ruby</option>
                    <option value="rbcon" >Ruby irb session</option>
                    <option value="splus" >S</option>
                    <option value="sql" >SQL</option>
                    <option value="scala" >Scala</option>
                    <option value="scheme" >Scheme</option>
                    <option value="smalltalk" >Smalltalk</option>
                    <option value="smarty" >Smarty</option>
                    <option value="squidconf" >SquidConf</option>
                    <option value="tcl" >Tcl</option>
                    <option value="tcsh" >Tcsh</option>
                    <option value="tex" >TeX</option>
                    <option value="text" >Text only</option>
                    <option value="vb.net" >VB.net</option>
                    <option value="vim" >VimL</option>
                    <option value="xml" >XML</option>
                    <option value="xml+cheetah" >XML+Cheetah</option>
                    <option value="xml+django" >XML+Django/Jinja</option>
                    <option value="xml+mako" >XML+Mako</option>
                    <option value="xml+myghty" >XML+Myghty</option>
                    <option value="xml+php" >XML+PHP</option>
                    <option value="xml+erb" >XML+Ruby</option>
                    <option value="xml+smarty" >XML+Smarty</option>
                    <option value="xslt" >XSLT</option>
                    <option value="yaml" >YAML</option>
                    <option value="c-objdump" >c-objdump</option>
                    <option value="cpp-objdump" >cpp-objdump</option>
                    <option value="d-objdump" >d-objdump</option>
                    <option value="objdump" >objdump</option>
                    <option value="rst" >reStructuredText</option>
                    <option value="sqlite3" >sqlite3con</option>
                </select>
		{{ form.private }} <label for="id_private">Private?</label>
            </td>
	    <td>{% render_honeypot_field %}</td>
        </tr>
        <tr>
	
            <td class="left">
                <label for="id_title">Title:</label>
            </td>
            <td class="center">
                {{ form.title }}
            </td>
        </tr>
        <tr>
            <td class="left">&nbsp;</td>
            <td class="center">
		<input type="hidden" name="captched" value="false" />
                <input type="submit" value="Paste!" id="id_submit" />
            </td>
        </tr>
    </table>
</form>
{% endblock %}