BD-incollo-master/urls.py
"""
    This file is part of BD-incollo.

    BD-incollo is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BD-incollo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with BD-incollo.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls.defaults import *

from Paste.models import Paste
from Paste.views import add_paste, view_paste, download_paste, report_paste, view_latest_pastes, search_pastes, discuss_paste, compare_pastes, mark_as_spam, view_latest_user_pastes, delete_paste

from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^media/(.*)', 'django.views.static.serve', {'document_root': '/home/incollo/Incollo/media'}),
    (r'^media-admin/(.*)', 'django.views.static.serve', {'document_root': '/home/incollo/Incollo/media-admin'}),
    (r'^admin/(.*)', admin.site.root),
    (r'^about', 'django.views.generic.simple.direct_to_template', {'template': 'about.html'}),
    (r'^bug', 'django.views.generic.simple.direct_to_template', {'template': 'bug.html'}),
    (r'^news', 'django.views.generic.simple.direct_to_template', {'template': 'news.html'}),
    (r'^$', add_paste),
    (r'^(?P<hash_key>[A-Fa-f0-9]+)$', view_paste),
    (r'^download/(?P<hash_key>[A-Fa-f0-9]+)', download_paste),
    (r'^report/(?P<hash_key>[A-Fa-f0-9]+)', report_paste),
    (r'^discuss/(?P<hash_key>[A-Fa-f0-9]+)', discuss_paste),
    (r'^compare/(?P<first_hash_key>[A-Fa-f0-9]+)/(?P<second_hash_key>[A-Fa-f0-9]+)', compare_pastes),
    (r'^latest-pastes$', view_latest_pastes),
    (r'^latest-personal-pastes$', view_latest_user_pastes),
    (r'^search/$', search_pastes),
    (r'^spam/(?P<hash_key>[A-Fa-f0-9]+)$', mark_as_spam),
    (r'^delete/(?P<hash_key>[A-Fa-f0-9]+)', delete_paste),
    (r'^comments/', include('django.contrib.comments.urls')),

)

assesment/Patebin_clone/pastebin_app/urls.py
from django.conf.urls import url
from . import views
from .views import PostCreateView, PostCreateView, PostUpdateView, PostDeleteView,SearchView

app_name = 'pastebin_app'
urlpatterns = [
    url(r'^search/$', views.SearchView.as_view(), name = 'search'),
    url(r'^$', views.PostCreateView.as_view(), name = 'root'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(),name='detail'),
    url(r'^update/(?P<slug>[\w-]+)/(?P<pk>\d+)/$', views.PostUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<slug>[\w-]+)/(?P<pk>\d+)/$', views.PostDeleteView.as_view(),name='delete'),
]

toDo_app/urls.py
from django.urls import path
from toDo_app.views import AddTodo, DeleteAll, DeleteItem, TodoView,Upload

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('addTodo/', AddTodo.as_view()),
    path('', TodoView.as_view()),
    path('deleteTodo/<int:todo_id>/',DeleteItem.as_view()),
    path('deleteAll/', DeleteAll.as_view()),
    path('upload/', Upload.as_view(), name = 'upload')
    #path('imageList/', Image_list.as_view(), name = 'images')


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

toDo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('toDo_app.urls')),
]

assesment/Patebin_clone/pastebin_app/models.py
from django.db import models
from django.urls import reverse
from .utils import get_unique_slug

# Create your models here.

class Post(models.Model):
    name = models.CharField(db_index=True, max_length=300, blank=False)
    content = models.TextField()
    slug = models.SlugField(max_length=140, unique=True)

    def __str__(self):
        return self.name
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'name', 'slug')
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("pastebin_app:detail",kwargs={'slug':self.slug,
                                                'pk': self.pk})

assesment/Patebin_clone/pastebin_app/views.py
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, DetailView,
                                CreateView, DeleteView
                                , UpdateView, ListView)
from . import models
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector

# Create your views here.
class SearchView(ListView):
    template_name = 'pastebin_app/search.html'
    model = models.Post

    def get(self, request, *args, **kwargs):
        q = request.GET.get('q', '')
        self.results = models.Post.objects.filter(name__icontains=q)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        return super().get_context_data(results=self.results, **kwargs)


class PostDetailView(DetailView):
    context_object_name = "post_detail"
    model = models.Post
    template_name = 'pastebin_app/detail.html'

class PostCreateView(CreateView):
    fields = ('name', 'content')
    model= models.Post

class PostUpdateView(UpdateView):
    fields = ('name','content')
    model = models.Post

class PostDeleteView(DeleteView):
    model = models.Post
    success_url = reverse_lazy("pastebin_app:root")

assesment/Patebin_clone/pastebin_app/templates/pastebin_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

assesment/Patebin_clone/pastebin_app/templates/pastebin_app/detail.html
{% extends "pastebin_app/base.html" %}

{% block body_block %}
  <h1>Welcome to the Pastebin Clone Assesment</h1>

  <p><h4>Name: {{post_detail.name}} </h4></p>
  <p>Content: {{post_detail.content}}</p><br><br>


   <a class="btn btn-primary" href="{% url 'pastebin_app:update' slug=post_detail.slug pk=post_detail.pk %}" role="button">Update</a></p>
   <a class="btn btn-warning" href="{% url 'pastebin_app:delete' slug=post_detail.slug pk=post_detail.pk %}" role="button">Delete</a>
{% endblock %}

assesment/Patebin_clone/pastebin_app/templates/pastebin_app/post_confirm_delete.html
{% extends "pastebin_app/base.html" %}

{% block body_block %}
<h1>Delete {{post.name}}?</h1>

<form class=""  method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" name="" value="Delete">
  <a class="btn btn-primary" href="{% url 'pastebin_app:detail' pk=post.pk %}" role="button">Cancel</a>

</form>
{% endblock %}

assesment/Patebin_clone/pastebin_app/templates/pastebin_app/post_form.html
{% extends "pastebin_app/base.html" %}

{% block body_block %}
<div class="container">
  <h1> Patebin Assesment Project</h1>
  <form id="searchform" action="{% url 'pastebin_app:search' %}" method="get" accept-charset="utf-8">

      <label for="searchbox">Search by name of the post: </label><br>
      <div class="row">
        <div class="col">
          <input class="form-control" id="searchbox" name="q" type="text" placeholder="Search">
        </div>
        <div class="col">
          <input class="btn btn-primary" type="submit" value="Search"/>

        </div>

      </div>


    </form><br>
    <h2>Create your post</h2><br>
    <div class="container-fluid">
      <form class="" method="post">

        <div class="form-group">
          {% csrf_token %}
          {{form.as_p}}
          <input class="btn btn-primary" type="submit" name="" value="PASTE">


       </div>
       </form>
    </div>



</div>








{% endblock %}

assesment/Patebin_clone/pastebin_app/templates/pastebin_app/search.html
{% extends "pastebin_app/base.html" %}

{% block body_block %}
<div class="container">


  {% if results %}
    <ul>
      {% for result in results %}
        <li> <a href="{{result.get_absolute_url}}"><p>{{result.slug}} </p></a></li>
        <p>Name: {{result.name}}</p>
        <p>Content: {{result.content}}</p>
      {% endfor %}

    </ul>
  {% else %}
    <p>No matched results.</p>
  {% endif %}
</div>
{% endblock %}